version: 2.1

orbs:
  gh: circleci/github-cli@2.2.0

executors:
  my-container:
    working_directory: ~/app
    docker:
      - image: cimg/rust:1.73.0-node

jobs:
  install-deps-and-build:
    executor: my-container
    description: Install all dependencies and build the project
    steps:
      - checkout
      - setup-target-platform-cmd
      - setup-trunk-cmd
      - build-tailwind-cmd
      - build-wasm-cmd
      - run:
          name: List the distribution build
          command: ls -al dist && mkdir -p workspace
      - run:
          name: Compress the output
          command: tar -czvf dist.tar.gz dist/* && mv dist.tar.gz workspace/
      - persist_to_workspace:
          root: workspace
          paths:
            - dist.tar.gz

  deploy-to-prod:
    executor: my-container
    steps:
      - attach_workspace:
          at: ~/app/workspace
      - run:
          name: Uncompress the dist tar
          command: tar -xzvf ./workspace/dist.tar.gz -C . 
      - deploy-to-prod-cmd

commands:
  setup-target-platform-cmd:
    steps:
      - run:
          name: Install Target Platform
          command: rustup target add wasm32-unknown-unknown
      - run:
          name: List Installed Targets
          command: rustup target list --installed

  setup-trunk-cmd:
    steps:
      - run:
          name: Install Trunk binary
          command: cargo install trunk
      - run:
          name: List Cargo's Installed Binaries
          command: cargo install --list

  build-tailwind-cmd:
    steps:
      - run:
          name: Build tailwindcss for production
          command: npx tailwindcss -c tailwind.config.js -i input.css  -o tailwind.css --minify
      - run:
          name: List generated output
          command: ls -al | grep "tailwind.css"

  build-wasm-cmd:
    steps:
      - run:
          name: Build Production wasm
          command: RUSTFLAGS=--cfg=web_sys_unstable_apis trunk build --release
      - run:
          name: List the output
          command: ls && ls dist

  deploy-to-prod-cmd:
    steps:
      - gh/setup
      - run: 
          name: Production Artifacts
          command: ls -alR
      - gh/clone:
          dir: repo/
      - run:
          name: Create new branch and all the stuff
          command: |
            #!/bin/bash
            # move into the repo
            cd repo
            
            # set basic identity
            git config user.email "flaviomoreira@gmail.com"
            git config user.name "Flavio Moreira"
          
            # add/view link to remote repo
            git remote -v
          
            # create new empty branch
            git switch --orphan release
          
            #copy build into repo
            cp ../dist/* ./ && ls -al
          
            # stage
            git add . && git status

            # commit the file
            echo "-- Commiting the changes --" && git commit -m "Initial release" 
          
            # setup upstream
            git branch --set-upstream-to origin/release && git branch -a
            
            # push the branch to remote repo
            git push --set-upstream origin release


workflows:
  build-and-deploy:
    jobs:
      - install-deps-and-build
      - deploy-to-prod:
          context: GITHUB-CONTEXT
          requires:
            - install-deps-and-build
